### ISSUE TITLE
关于新添加的功能的使用

### ISSUE THREAD

**Issue by kamikyo** [cuteant/SpanNetty#34]
看到您在DotNetty.Buffers里添加了大量的Span,Memory,ArrayPool相关的类进去。我想问一下，如何才能使用SpanNetty才能令您新添加的这些东西生效以提升性能。感觉是需要显示调用相关的buffer才会生效吗？

**Comment by cuteant** [comment]
可以在业务处理中，采用 ArrayPooledBuffer 代替 UnpooledBuffer
ByteBufferReader等同于 [SequenceReader](https://docs.microsoft.com/en-us/dotnet/api/system.buffers.sequencereader-1?view=net-5.0) ，兼容了.netfx、netstandard2.0

**Comment by kamikyo** [comment]
多谢大佬指点，大佬要是有精力开一个讲解dotnetty源码系列的文章的话那就是真的造福社区大众了。
