### ISSUE TITLE
句柄缓慢增长

### ISSUE THREAD

**Issue by MetSystem** [cuteant/SpanNetty#37]
SpanNetty 0.7.2012.2221 
940家设备1分钟传一次，大概整点传
```c#
Environment.SetEnvironmentVariable("io.netty.noPreferDirect", "true");

     var dispatcher = new DispatcherEventLoopGroup();
                bossGroup = dispatcher;
                workerGroup = new WorkerEventLoopGroup(dispatcher, workerEventThreadCount);
       bootstrap
                    .Option(ChannelOption.SoBacklog, 256)
                    .Option(ChannelOption.Allocator, PooledByteBufferAllocator.Default)
                    .Handler(new LoggingHandler("SEV-LITN", LogLevel.ERROR))
                    .ChildOption(ChannelOption.SoKeepalive, true)
                    .ChildOption(ChannelOption.TcpNodelay, true)
                    .ChildOption(ChannelOption.SoSndbuf, 8 * 1024)
                    .ChildOption(ChannelOption.SoRcvbuf, 16 * 1024)
                    .ChildOption(ChannelOption.Allocator, PooledByteBufferAllocator.Default)

                    .ChildHandler(new ActionChannelInitializer<IChannel>(channel =>
                    {
                        IChannelPipeline pipeline = channel.Pipeline;
                        pipeline.AddLast(new LoggingHandler("SEV-CONN", LogLevel.INFO));
                        pipeline.AddLast("timeout", new IdleStateHandler(3 * 60, 3 * 60, 3 * 60));

                        pipeline.AddFirst("device", new DeviceHandler());
                        pipeline.AddLast("LineBasedFrameDecoder", new LineBasedFrameDecoder(1024));
                        pipeline.AddLast("StringDecoder", new StringDecoder());
                        pipeline.AddLast("CustomEncoder", new CustomEncoder());
                        pipeline.AddLast("Check", new CheckChannelHandler());
                        pipeline.AddLast("default", new DefaultServerHandler());
                    }));

                IChannel boundChannel = await bootstrap.BindAsync(AppSettings.Port);
                Console.ReadLine();

```
# 服务端应答集成设备代码
```
  var data = BuildPacket(context.Message.Content.ToString());
                if (devcieInfo.Channel.IsWritable && devcieInfo.Channel.IsActive)
                {
                    devcieInfo?.Channel.WriteAndFlushAsync(data);
                }
                else if (!devcieInfo.Channel.IsWritable)
                {
                    devcieInfo?.Channel.WriteAndFlushAsync(data).Wait(TimeSpan.FromSeconds(5));
                }
```

# 流程：
```
接入设备=》Server 产生消息=>rabbitmq=>业务消费消息=》产生应答消息=》rabbitmq =》Server 消费消息=》设备接入
```

# 日志中常见异常
## 异常1
```c#
DotNetty.Transport.Channels.ChannelException: Exception of type 'DotNetty.Transport.Channels.ChannelException' was thrown.
 ---> DotNetty.Transport.Libuv.Native.OperationException: ECONNRESET (ECONNRESET) : connection reset by peer
   --- End of inner exception stack trace ---
```

## 异常2
```c#
00:00:50.032 [ERR] ExceptionCaught:Message=>远程主机强迫关闭了一个现有的连接。 ,StackTrace=>   at DotNetty.Transport.ThrowHelper.ThrowSocketException(SocketError err)
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel`2.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation`2 operation)
System.Net.Sockets.SocketException (10054): 远程主机强迫关闭了一个现有的连接。
   at DotNetty.Transport.ThrowHelper.ThrowSocketException(SocketError err)
   at DotNetty.Transport.Channels.Sockets.AbstractSocketByteChannel`2.SocketByteChannelUnsafe.FinishRead(SocketChannelAsyncOperation`2 operation)
```

**Comment by MetSystem** [comment]
net 5.0

**Comment by yyjdelete** [comment]
如果句柄数是在一定范围内反复增减, 不会一直涨到几十万的话, 而且没连接的时候也会定时增长的话, 

那可能就是我上次发现的那个问题
https://github.com/dotnet/runtime/issues/47752
https://github.com/cuteant/SpanNetty/blob/future/src/DotNetty.Common/Concurrency/XThread.cs#L124
这个是这里的Task.Delay().Wait()造成的, 根据版本历史, 最初用主要是因为netstandard2.0之前不支持`Thread.Sleep()`.

因为现在不需要再支持netstandard1.x的原因, 这里可以考虑用回`Thread.Sleep(ms)`, 或者改用`new ManualResetEventSlim().Wait(ms)`(这个netstandard1.3好像也支持, 参考https://stackoverflow.com/a/16374324)

**Comment by MetSystem** [comment]
我尝试下，非常感谢

**Comment by MetSystem** [comment]
https://github.com/cuteant/SpanNetty/blob/7e2252b2dfe5cbaf36bf6c15b8219b98685c2bdb/src/DotNetty.Common/Utilities/HashedWheelTimer.cs#L431
这个里面是不是也需要改。

今天用用dotnetty源码改了XThread.cs 发现稍微缓解了增长速度，但还是存在（spannetty改了后生成环境找不到DLL,所以改成dotnetty）。

**Comment by yyjdelete** [comment]
1. HashedWheelTimer如果你用到了可以改下看看, 框架本身只是移植了, 但没有用这个类


其他句柄就不知道是什么了, 一般情况下句柄数基本上应该等于线程数+连接数+一个基本稳定的值, 如果没有一直启动新线程或者建立连接应该比较稳定的

2. 如果你现在是用的libuv也可以试试不开还会不会有句柄
我对这行代码是如何工作的存在疑问, 感觉父类的实现才是正确的, 但没时间去测试
https://github.com/cuteant/SpanNetty/blob/7e2252b2dfe5cbaf36bf6c15b8219b98685c2bdb/src/DotNetty.Transport.Libuv/LoopExecutor.cs#L181-L184

3. 如果你想的话可以用procexp或者process hacker(均需要管理员权限, 属于系统工具, 部分杀软可能报毒)自己检查下对应一直在增加的句柄是什么东西
process hacker, 注意关掉选项里的HIDE
![image](https://user-images.githubusercontent.com/1819074/116231563-9e1e2300-a78b-11eb-9408-bd6a8b0d6a01.png)
procexp, View/Show Lower Pane+Lower Pane View=HANDLEs
![image](https://user-images.githubusercontent.com/1819074/116231686-c9a10d80-a78b-11eb-93a7-5b4e576ae927.png)

**Comment by MetSystem** [comment]
大佬帮忙看看

[IotServer.exe.txt](https://github.com/cuteant/SpanNetty/files/6385152/IotServer.exe.txt)

**Comment by yyjdelete** [comment]
998个端口,6914个Event,1781个线程
感觉你这个线程数有点多得不正常了, 建议调试下看看代码都在跑什么, 有可能是业务代码本身的问题

**Comment by MetSystem** [comment]
libuv 设置10

**Comment by MetSystem** [comment]
ProcessHacker显示的进程几万个
[ProcessHacker.txt](https://github.com/cuteant/SpanNetty/files/6388451/ProcessHacker.txt)

**Comment by yyjdelete** [comment]
这种只能你自己调试下了

如果开发环境, vs调试涨上去后(或者直接附加到已经涨上去的进程)直接暂停, 然后`调试/窗口/并行堆栈 或者 线程`/vscode看线程, 自己检查下大部分线程都在跑什么堆栈, 感觉应该是有大量的线程都在跑同一个东西的?
如果生产环境, 自己在服务器上抓个dump(任务管理器右键, 创建dump), 复制回开发环境, 丢vs然后步骤同上, 或者丢windbg里面看看吧(用法可以参考https://www.cnblogs.com/huangxincheng/p/14388296.html)

**Comment by MetSystem** [comment]
好，多谢指导
