### ISSUE TITLE
Should `release/0.7.x` be merged to `main`?

### ISSUE THREAD

**Issue by yyjdelete** [cuteant/SpanNetty#50]
Seems some commits is only on `release/0.7.x` but not `main`?
https://github.com/cuteant/SpanNetty/compare/release/0.7.x
>This branch is 8 commits ahead, 38 commits behind main.

**Comment by cuteant** [comment]
不需要，都是些配置性的修改
![image](https://user-images.githubusercontent.com/9393576/119250931-14b90f80-bbd6-11eb-8d73-597c2c6e6755.png)

**Comment by cuteant** [comment]
我再看看，有几个关于Azure DevOps测试的修改
